language: python
python:
  - "3.6"
before_install:
  - export TZ=Asia/Singapore
  - time
script:
  - python hn-ratio.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
